name: empsol_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  http: ^1.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  excel: ^2.0.6
  file_picker: ^5.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0 
  google_maps_flutter: ^2.1.0  # for Google Maps

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true